name: sr_laravel
services:
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - ../src:/app
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /app/vendor
      - /app/bootstrap/cache
      - /app/storage
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
  php-worker:
    image: sr_laravel-php:latest
    entrypoint: php artisan queue:work
    env_file: .env
    volumes:
      - ../src:/app
      - /app/vendor
      - /app/bootstrap/cache
      - /app/storage
  nginx:
    image: nginx:1.24-bullseye
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: postgres:14.8-bullseye
    env_file: .db.env
    