name: sr_laravel
services:
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - ../src:/app
      - /app/vendor
      - /app/bootstrap/cache
      - /app/storage
  nginx:
    image: nginx:1.24-bullseye
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    